"""aggiunge consegnato a ordine

Revision ID: 9ffaa9fd4479
Revises: d6bcfd968dc8
Create Date: 2026-07-07 19:59:05.035815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffaa9fd4479'
down_revision = 'd6bcfd968dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('consegnato', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('riga_ordine', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('evaso', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('modificato', sa.Boolean(), nullable=False, server_default=sa.false())
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('riga_ordine', schema=None) as batch_op:
        batch_op.drop_column('modificato')
        batch_op.drop_column('evaso')

    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.drop_column('consegnato')
    # ### end Alembic commands ###
