"""Aggiunge confezioni e descrizione prodotto

Revision ID: d6bcfd968dc8
Revises: 
Create Date: 2026-07-07 16:44:20.974160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bcfd968dc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confezione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prodotto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('moltiplicatore', sa.Float(), nullable=True),
    sa.Column('prezzo_extra', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['prodotto_id'], ['prodotto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prodotto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrizione', sa.Text(), nullable=True))

    with op.batch_alter_table('riga_ordine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confezione_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantita_magazzino', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'confezione', ['confezione_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riga_ordine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantita_magazzino')
        batch_op.drop_column('confezione_id')

    with op.batch_alter_table('prodotto', schema=None) as batch_op:
        batch_op.drop_column('descrizione')

    op.drop_table('confezione')
    # ### end Alembic commands ###
